# Generated by Django 5.2.14 on 2026-05-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_tablebooking_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон гостя'),
        ),
    ]
