# Generated by Django 5.2.14 on 2026-05-15 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_phone_to_tablebooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tablebooking',
            index=models.Index(fields=['status', 'date'], name='booking_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='tablebooking',
            index=models.Index(fields=['status'], name='booking_status_idx'),
        ),
    ]
