# Generated by Django 5.2.14 on 2026-07-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_tablebooking_booking_status_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='remarked_reserve_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID брони в Remarked'),
        ),
    ]
