# Generated by Django 5.2.14 on 2026-07-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_tablebooking_remarked_reserve_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='remarked_room_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID зала в Remarked'),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Зона/зал'),
        ),
    ]
