# Generated by Django 5.2.14 on 2026-07-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_tablebooking_remarked_room_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='remarked_table_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID стола в Remarked'),
        ),
    ]
