# Generated by Django 5.2.14 on 2026-07-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_tablebooking_remarked_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='remarked_room_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID зала в Remarked'),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='remarked_table_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID стола в Remarked'),
        ),
    ]
