services:
  # База данных PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      # Указываем, куда стучаться (имя контейнера с БД)
      - DB_HOST=db
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      # Имя базы данных
      - DB_NAME=${POSTGRES_DB}
      
      # КРИТИЧНО: Режим пулирования
      - POOL_MODE=transaction
      # Максимальное количество соединений с самой БД
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=100
      # Отключаем SSL для внутренней Docker-сети (если не настроено иначе)
      - AUTH_TYPE=scram-sha-256 # Или md5, в зависимости от настроек Postgres
    ports:
      - "6432:6432" # Стандартный порт PgBouncer
    depends_on:
      db:
        condition: service_healthy

  # Redis (для кэша и брокера Celery)
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Основное Django приложение
  backend:
    build: .
    container_name: django_backend
    volumes:
      - .:/app/backend # Монтируем код для горячей перезагрузки при разработке
      - ./logs:/app/backend/logs # Пробрасываем папку логов на хост-машину
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Команда для разработки с автоматической перезагрузкой
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_started

  # Воркер Celery (использует тот же Dockerfile)
  worker:
    build: .
    container_name: celery_worker
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app/backend
      - ./logs:/app/backend/logs # Пробрасываем папку логов на хост-машину
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_started

  # Celery Beat (планировщик периодических задач)
  beat:
    build: .
    container_name: celery_beat
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app/backend
      - ./logs:/app/backend/logs
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_started

volumes:
  pg_data:
