# Generated by Django 5.2.14 on 2026-05-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_userdevice_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Категория')),
                ('segment', models.CharField(blank=True, max_length=50, verbose_name='Сегмент')),
                ('total_users', models.PositiveIntegerField(default=0, verbose_name='Всего получателей')),
                ('delivered_count', models.PositiveIntegerField(default=0, verbose_name='Доставлено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
            ],
            options={
                'verbose_name': 'Push-кампания',
                'verbose_name_plural': 'Push-кампании',
                'ordering': ['-created_at'],
            },
        ),
    ]
