# Generated by Django 5.2.14 on 2026-08-03 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_push_campaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(db_index=True, max_length=4096, verbose_name='FCM токен устройства')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные (data)')),
                ('context', models.CharField(max_length=20, verbose_name='Контекст получения')),
                ('is_own_channel', models.BooleanField(default=False, help_text="True, если в data есть наша внутренняя метка _source — иначе пуш пришёл в обход backend'а (например, от Remarked).", verbose_name="Отправлено нашим backend'ом")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Записано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Факт получения push',
                'verbose_name_plural': 'Факты получения push',
                'ordering': ['-created_at'],
            },
        ),
    ]
