# Generated by Django 5.2.14 on 2026-05-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_user_city_idx_user_user_date_joined_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='ID чата менеджера в Telegram для авторизации в боте.', max_length=100, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
