# Generated by Django 5.2.14 on 2026-07-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_gender_email_birthday_remarked_guest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Баланс бонусов гостя из CRM Remarked (поле `bonuses`). Обновляется при синхронизации.', max_digits=12, verbose_name='Кэшбек'),
        ),
    ]
