# Generated by Django 5.2.14 on 2026-05-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('working_hours', models.CharField(max_length=255, verbose_name='Часы работы')),
                ('tour_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на 3D-тур')),
                ('twogis_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на 2GIS')),
            ],
            options={
                'verbose_name': 'Информация о ресторане',
                'verbose_name_plural': 'Информация о ресторане',
            },
        ),
    ]
