# Generated by Django 5.2.14 on 2026-05-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurantinfo_contacts_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='concept_description',
            field=models.TextField(blank=True, default='', verbose_name='Описание концепции'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='core/', verbose_name='Заглавное изображение'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='hero_video_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL заглавного видео'),
        ),
    ]
