# Generated by Django 5.2.14 on 2026-05-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_hero_and_concept_to_restaurantinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10, unique=True, verbose_name='Платформа')),
                ('min_version', models.CharField(max_length=20, verbose_name='Минимальная версия (force update)')),
                ('latest_version', models.CharField(max_length=20, verbose_name='Последняя версия (optional update)')),
                ('store_url', models.URLField(blank=True, verbose_name='Ссылка на магазин')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Версия приложения',
                'verbose_name_plural': 'Версии приложения',
            },
        ),
    ]
