# Generated by Django 5.2.14 on 2026-05-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='feedback_url',
            field=models.URLField(blank=True, null=True, verbose_name='Обратная связь (URL)'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='google_maps_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Google Maps'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='yandex_maps_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Яндекс.Карты'),
        ),
    ]
