# Generated by Django 5.2.14 on 2026-05-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_restaurantinfo_feedback_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('main_hall', 'Главный зал'), ('bar', 'Бар'), ('private', 'Приватная комната'), ('terrace', 'Терраса'), ('other', 'Другое')], default='main_hall', max_length=20, verbose_name='Зона')),
                ('image', models.ImageField(upload_to='interior/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись (необязательно)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фото интерьера',
                'verbose_name_plural': 'Фото интерьера',
                'ordering': ['zone', 'order'],
            },
        ),
    ]
