# Generated by Django 5.2.14 on 2026-05-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_interiorphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='booking_deposit_note',
            field=models.CharField(blank=True, default='', help_text='Напр.: «При бронировании приват-зала необходим депозит. Позвоните менеджеру.»', max_length=500, verbose_name='Текст предупреждения о депозите'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='booking_deposit_required',
            field=models.BooleanField(default=False, verbose_name='Требуется депозит при бронировании'),
        ),
    ]
