# Generated by Django 5.2.14 on 2026-05-14 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_working_hours_note_to_restaurantinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantinfo',
            name='hero_image',
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='working_hours_note',
            field=models.CharField(blank=True, default='', help_text='Разовое уведомление, которое Flutter покажет гостям (напр.: «Закрыто 1 января»).', max_length=500, verbose_name='Временное изменение режима'),
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='core/hero/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('restaurant_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='core.restaurantinfo', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Слайд главного экрана',
                'verbose_name_plural': 'Слайды главного экрана',
                'ordering': ['order'],
            },
        ),
    ]
