# Generated by Django 5.2.14 on 2026-05-21 09:19

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_appversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantinfo',
            name='hero_video_url',
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='JPEG или PNG, горизонтальное, минимум 800×450 px, не более 10 МБ.', upload_to='core/hero/', validators=[apps.core.models.validate_hero_image], verbose_name='Изображение'),
        ),
    ]
