# Generated by Django 5.2.14 on 2026-05-26 05:14

import utils.upload_paths
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_restaurantinfo_hero_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Любой формат и ориентация — автоматически обрезается до 16:9 и конвертируется в JPEG. Минимум 800×450 px, не более 10 МБ.', upload_to=utils.upload_paths.hero_image_upload, validators=[utils.validators.validate_hero_image], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='interiorphoto',
            name='image',
            field=models.ImageField(help_text='Фото отображается fullscreen без обрезки. Рекомендуется горизонтальная ориентация, минимум 1200 px по ширине.', upload_to=utils.upload_paths.interior_image_upload, verbose_name='Фото'),
        ),
    ]
