# Generated by Django 5.2.14 on 2026-07-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_visitrule_remove_restaurantinfo_visit_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantinfo',
            name='booking_deposit_note',
        ),
        migrations.RemoveField(
            model_name='restaurantinfo',
            name='booking_deposit_required',
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='privacy_policy',
            field=models.URLField(blank=True, verbose_name='Политика обработки ПД'),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='terms_of_service',
            field=models.URLField(blank=True, verbose_name='Пользовательское соглашение'),
        ),
    ]
