# Generated by Django 5.2.14 on 2026-07-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_restaurantinfo_booking_deposit_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantinfo',
            name='google_maps_link',
        ),
        migrations.RemoveField(
            model_name='restaurantinfo',
            name='yandex_maps_link',
        ),
    ]
