# Generated by Django 5.2.14 on 2026-05-10 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_count', models.PositiveIntegerField(default=1, verbose_name='Количество гостей (включая себя)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время бронирования')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='events.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись на мероприятие',
                'verbose_name_plural': 'Записи на мероприятия',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
