# Generated by Django 5.2.14 on 2026-05-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_format_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', 'date_time'], name='event_active_date_idx'),
        ),
    ]
