# Generated by Django 5.2.14 on 2026-05-21 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_event_active_date_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhotoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/reports/', verbose_name='Фотография')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_reports', to='events.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Фото отчёта',
                'verbose_name_plural': 'Фотоотчёты мероприятий',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
