# Generated by Django 5.2.14 on 2026-05-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventphotoreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_places',
            field=models.PositiveIntegerField(default=0, help_text='0 означает отсутствие ограничений на количество мест', verbose_name='Количество разрешенных мест'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(help_text='Любой формат и ориентация — фото автоматически обрезается до 16:9 и конвертируется в JPEG. Рекомендуемый минимум: 1200×675 px.', upload_to='events/images/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='eventphotoreport',
            name='image',
            field=models.ImageField(help_text='Фото отображается fullscreen без обрезки. Рекомендуется горизонтальная ориентация, минимум 1200 px по ширине.', upload_to='events/reports/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Необязательное. Любой формат — автоматически обрезается до 16:9 и конвертируется в JPEG. Рекомендуемый минимум: 1200×675 px.', null=True, upload_to='news/images/', verbose_name='Изображение'),
        ),
    ]
