# Generated by Django 5.2.14 on 2026-05-26 05:14

import utils.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_max_places_alter_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(help_text='Любой формат и ориентация — фото автоматически обрезается до 16:9 и конвертируется в JPEG. Рекомендуемый минимум: 1200×675 px.', upload_to=utils.upload_paths.event_image_upload, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='eventphotoreport',
            name='image',
            field=models.ImageField(help_text='Фото отображается fullscreen без обрезки. Рекомендуется горизонтальная ориентация, минимум 1200 px по ширине.', upload_to=utils.upload_paths.event_report_image_upload, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Необязательное. Любой формат — автоматически обрезается до 16:9 и конвертируется в JPEG. Рекомендуемый минимум: 1200×675 px.', null=True, upload_to=utils.upload_paths.news_image_upload, verbose_name='Изображение'),
        ),
    ]
