import uuid

from django.core.cache import cache
from rest_framework import status
from rest_framework.response import Response

IDEMPOTENCY_TTL = 86400  # 24 hours
_PROCESSING = "__processing__"


class IdempotencyMixin:
    """
    Makes POST idempotent via the Idempotency-Key header (UUID generated by client).
    Cache key is scoped per user so the same UUID from two users is independent.
    On 500-level exceptions the lock is released so the client can retry safely.
    """

    def _idempotency_cache_key(self, raw_key: str) -> str:
        user_id = getattr(self.request.user, "id", "anon")
        return f"idempotency:{user_id}:{raw_key}"

    def create(self, request, *args, **kwargs):
        raw_key = request.headers.get("Idempotency-Key", "").strip()

        if not raw_key:
            return Response(
                {"detail": "Заголовок Idempotency-Key обязателен."},
                status=status.HTTP_400_BAD_REQUEST,
            )
        try:
            uuid.UUID(raw_key)
        except ValueError:
            return Response(
                {"detail": "Idempotency-Key должен быть корректным UUID."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        cache_key = self._idempotency_cache_key(raw_key)

        cached = cache.get(cache_key)
        if cached is not None:
            if cached == _PROCESSING:
                return Response(
                    {"detail": "Запрос уже обрабатывается. Повторите через несколько секунд."},
                    status=status.HTTP_409_CONFLICT,
                )
            return Response(cached["data"], status=cached["status_code"])

        # Atomic set-if-not-exists (Redis SET NX) — prevents race condition
        if not cache.add(cache_key, _PROCESSING, IDEMPOTENCY_TTL):
            cached = cache.get(cache_key)
            if cached and cached != _PROCESSING:
                return Response(cached["data"], status=cached["status_code"])
            return Response(
                {"detail": "Запрос уже обрабатывается."},
                status=status.HTTP_409_CONFLICT,
            )

        try:
            response = super().create(request, *args, **kwargs)
        except Exception:
            cache.delete(cache_key)
            raise

        cache.set(
            cache_key,
            {"status_code": response.status_code, "data": response.data},
            IDEMPOTENCY_TTL,
        )
        return response
