# Generated by Django 5.2.14 on 2026-05-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_weight_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='video_processed',
            field=models.FileField(blank=True, null=True, upload_to='dishes/videos/processed/', verbose_name='Обработанное видео'),
        ),
        migrations.AddField(
            model_name='dish',
            name='video_status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('ready', 'Готово'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['is_active', 'video_status'], name='menu_dish_is_acti_362481_idx'),
        ),
    ]
