# Generated by Django 5.2.14 on 2026-05-26 05:14

import utils.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_video_processed_dish_video_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(help_text='Любой формат и ориентация — фото автоматически обрезается до 16:9 и конвертируется в JPEG. Рекомендуемый минимум: 1200×675 px.', upload_to=utils.upload_paths.dish_image_upload, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 или MOV, вертикальное видео 9:16 (рекомендуется 720×1280). Будет автоматически транскодировано в фоне — статус виден в поле «Статус видео».', null=True, upload_to=utils.upload_paths.dish_video_upload, verbose_name='Видео (для ленты)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='video_processed',
            field=models.FileField(blank=True, null=True, upload_to=utils.upload_paths.dish_video_processed_upload, verbose_name='Обработанное видео'),
        ),
    ]
